stages:
  preprocess:
    cmd: python preprocess.py
    deps:
    - preprocess.py
    - Titanic-Dataset.csv
    outs:
    - data/train.csv
    - data/test.csv

  train:
    cmd: python train.py
    deps:
    - train.py
    - data/train.csv
    outs:
    - model/model.pkl
    
  validate:
    cmd: python validate.py
    deps:
      - data/test.csv
      - model/model.pkl
      - validate.py
    metrics:
      - results/metrics.json
    plots:
      - results/confusion_matrix.png
